fix: adjust nav bar name
watchout-tw/watchout-common-functions pull request #146
Opened 2023-02-14 09:46 UTC by KTRNJack

# Whst's Changed

## commit id : 99e5209
問題 : 登入後名稱不會改變。
解法 :
目前的話，如果不是會跳轉頁面的話，會因為元件已經被渲染過，因此值不會去做改變。
因此多增加監聽 function ，如果已經登入後，去重新拿取會員資料，然後再來做顯示

2023-02-16 04:58 UTC, wesley100002001 requested changes

2023-02-16 04:58 UTC, wesley100002001 commented on components/NavBar.vue
> +    // 每当 question 改变时，这个函数就会执行
這邊怎麼會有簡體字註解？

2023-02-16 04:58 UTC, wesley100002001 commented on components/NavBar.vue
> +        this.internalName()
應該可以把 internalName 寫成 computed，不需要 watch citizenObj

2023-02-16 05:37 UTC, KTRNJack commented on components/NavBar.vue
> +    // 每当 question 改变时，这个函数就会执行
對不起!!! 我的錯!!!

2023-02-20 01:29 UTC, wesley100002001 approved these changes

2023-02-21 05:36 UTC, merged